[package]
name = "topo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hwloc = "0.5"
cgroups-rs = "0.3"
nix = "0.26.2"
libc = "0.2"
